language: python
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make travis
env:
  global:
  - secure: PE/jnSPZTh3j5JTKEaSNw8CCbpejNdxyAZ1NweNkOPwjQWIOzLpREOvO5CbdZ0U4LFRq5C+/f29M6ruMS8L8M3SoAyYSc6FWaM+2X6T9auSJbkh2DoYBj9lJRMQz5fjhglU/0s65gBwa8VsqNq5lG9VOWc81ML7/OMHOIB7KgIGEhKlpSlR+ODQi9QKpi0RBYmrSkVWq1asWCmBeWDCNpVXoXxtqhIIsUVK+E3xNhjz0Cjvy27l4I9gbXX6kLhSjSs/rzpISrlCdAfUdqllcvIT3fhAKZpHM6UbT3hxnZAY6OLWeCUeOFz8fh1v1tBrAfh+IW3jiwAvMIp5ny/3ECQrQKfLxQG02/Jg9nJD0f2P51YmDpHA6jnYXrv9ZZhQ2QSVa+sFaCsrYuYEkSRHZckeBfRBY64T8YsNZnPNbRnVnMogou7Eu+7bsQI2USdU3MIJs16/LWKh3sWdIQvH/DiJ9RgcLnbR+sKytxbz1lQCpoZUYUIKRqtNNuTO3iLXcuoaMJitRhvvLm5U39IZaLuzxV+kZZHJM6Pc6Uf3ZyPHFzBdvEspecVjAGLGRFmUh3wjhQsfN0s5OzgPJ6qyeo8IynpH6cmn3BH83Dc/MazYBw3lo0ZNJYEeiqpUnshW9CqEYHghF4Yl5Z75MPz9HxmEwCscGwJVL/wCzgrgZc6k=
